image: Ubuntu1804 # образ для сборки

stack: node 14.17.0 # окружение

branches:
  only:
    - main # ветка git

cache: node_modules # кеширование

build: off # отключаем встроенную в appveyor систему сборки

build_script:
  - yarn install
  - yarn run build # команда сборки

test_script:
test: off
  #  - yarn run test && npm test # скрипт тестирования

deploy_script: # скрипт развёртывания
  - git config --global user.email "m-mik@ro.ru"
  - git config --global user.name "GegamGrigoryan"
  - git config --list
  - git checkout -b deploy
  - git add -A
  - git commit -m "first commit"
  - git push -f origin deploy
  - git push --force --quiet "https://${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}@github.com/GegamGrigoryan/https://github.com/GegamGrigoryan/Top_task.git"
